version: "1.1.1"

usage_steps:
  en:
    - "1. Select a folder to scan"
    - "2. Choose the maximum depth level"
    - "3. Select output options (CSV/PDF)"
    - "4. Choose output location"
    - "5. Click 'Start Processing'"
  zh_tw:
    - "1. 選擇要掃描的資料夾"
    - "2. 選擇最大層級深度"
    - "3. 選擇輸出選項 (CSV/PDF)"
    - "4. 選擇輸出位置"
    - "5. 點擊開始處理"
  zh_cn:
    - "1. 选择要扫描的文件夹"
    - "2. 选择最大层级深度"
    - "3. 选择输出选项 (CSV/PDF)"
    - "4. 选择输出位置"
    - "5. 点击开始处理"

translations:
  en:
    window_title: "Directory Scanner"
    select_folder: "Select Folder"
    no_folder_selected: "No folder selected"
    max_depth: "Select Folder Depth:"
    generate_csv: "Generate CSV"
    generate_pdf: "Generate PDF"
    select_output: "Select Output Location"
    no_output_selected: "No output location selected"
    start_processing: "Start Processing"
    menu_help: "Help"
    menu_usage: "Usage Guide"
    menu_about: "About"
    language: "Language"
    status_ready: "Ready"
    status_processing: "Processing..."
    status_complete: "Complete"
    status_error: "Error: {}"
    error_no_input_folder: "Error: Please select an input folder"
    error_no_output_folder: "Error: Please select an output location"
    error_no_output_format: "Error: Please select at least one output format (CSV or PDF)"
    company_name: ""
    copyright: "Copyright © 2024 HuHu Tech. All rights reserved."
    version_text: "Version: {}"
    project_name: "Project Name:"
    report_date: "Report Date:"
    handover_form: "Handover Form"
    prepared_by: "DIT:"
    received_by: "Received by:"
    date: "Date:"
    signature: "Signature:"
    file_type: "File Type"
    file_size: "File Size"
    creation_time: "Creation Time"
    directory_structure: "Directory Structure"
    table_view: "Table View"
    select_folder_placeholder: "Please select a folder..."
    select_output_placeholder: "Please select output location..."
    browse_button: "View..."
    total_size: "Total Size: {}"

  zh_tw:
    window_title: "目錄掃描器"
    select_folder: "選擇資料夾"
    no_folder_selected: "未選擇資料夾"
    max_depth: "選擇顯示層數:"
    generate_csv: "生成 CSV"
    generate_pdf: "生成 PDF"
    select_output: "選擇輸出位置"
    no_output_selected: "未選擇輸出位置"
    start_processing: "開始處理"
    menu_help: "幫助"
    menu_usage: "使用說明"
    menu_about: "關於"
    language: "語言"
    status_ready: "就緒"
    status_processing: "處理中..."
    status_complete: "完成"
    status_error: "錯誤: {}"
    error_no_input_folder: "錯誤：請選擇要掃描的資料夾"
    error_no_output_folder: "錯誤：請選擇輸出位置"
    error_no_output_format: "錯誤請至少選擇一種輸出格式(CSV 或 PDF)"
    company_name: ""
    copyright: "版權所有 © 2024 HuHu Tech。保留所有權利。"
    version_text: "版本：{}"
    project_name: "項目名稱："
    report_date: "報表日期："
    handover_form: "交接單"
    prepared_by: "DIT："
    received_by: "接收人："
    date: "日期："
    signature: "簽名："
    file_type: "檔案類型"
    file_size: "檔案大小"
    creation_time: "建立時間"
    directory_structure: "目錄結構"
    table_view: "表格檢視"
    select_folder_placeholder: "請選擇掃描路徑..."
    select_output_placeholder: "請選擇輸出位置..."
    browse_button: "瀏覽..."
    total_size: "總大小：{}"

  zh_cn:
    window_title: "目录扫描器"
    select_folder: "选择文件夹"
    no_folder_selected: "未选择文件夹"
    max_depth: "选择显示层数:"
    generate_csv: "生成 CSV"
    generate_pdf: "生成 PDF"
    select_output: "选择输出位置"
    no_output_selected: "未选择输出位置"
    start_processing: "开始处理"
    menu_help: "帮助"
    menu_usage: "使用说明"
    menu_about: "关于"
    language: "语言"
    status_ready: "就绪"
    status_processing: "处理中..."
    status_complete: "完成"
    status_error: "错误: {}"
    error_no_input_folder: "错误：请选择要扫描的文件夹"
    error_no_output_folder: "错误：请选择输出位置"
    error_no_output_format: "错误：请至少选择一种输出格式（CSV 或 PDF）"
    company_name: ""
    copyright: "版权所有 © 2024 HuHu Tech。保留所有权利。"
    version_text: "版本：{}"
    project_name: "项目名称："
    report_date: "报表日期："
    handover_form: "交接单"
    prepared_by: "DIT："
    received_by: "接收人："
    date: "日期："
    signature: "签名："
    file_type: "文件类型"
    file_size: "文件大小"
    creation_time: "创建时间"
    directory_structure: "目录结构"
    table_view: "表格视图"
    select_folder_placeholder: "请选择扫描路径..."
    select_output_placeholder: "请选择输出位置..."
    browse_button: "浏览..."
    total_size: "总大小：{}"